name: CI for ssd

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: maven:3.9.11-eclipse-temurin-21-noble

    steps:
      - name: Start CI
        run: echo "Start"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Clean, test and package  with maven
        run: |-
          if [ -x "./mvnw" ]; then
            ./mvnw -B clean test package
          else
            mvn -B clean test package
          fi

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-report
          path: ./target/*.jar

      - name: End CI
        run: echo "End"
